apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: jenkins.stormcloaks.com
      http:
        paths:
          - path: /
            backend:
              serviceName: jenkins
              servicePort: 8080